FROM php:7.4.11-apache-buster
RUN sudo apt update && apt install -y curl wget gnupg2 ca-certificates lsb-release apt-transport-https
#RUN apt-get update && apt-get install php7 && apt-get clean
EXPOSE 80
